# This file is a template, and might need editing before it works on your project.

image: golang:latest

stages:
  - build
# working directory test_code
website_linux_amd64:
  only:
    changes:
      - code/**/*
  before_script:
    - ls -lah
    - ln -s /builds /go/src/gitlab.com
    - go get -u github.com/gorilla/mux
    - go get -u github.com/lib/pq
    - go get -u github.com/gobuffalo/packr
    - go get -u github.com/gobuffalo/packr/packr

  stage: build
  script:
    - make build_linux
  artifacts:
    paths:
      - code/release/website_linux_amd64